# Generated by Django 5.1.6 on 2025-02-28 09:32

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180406_1557'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('data', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='concealed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted',
        ),
    ]
