# Generated by Django 4.1 on 2022-08-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0003_week_footer_alter_week_headline"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Sortierung"),
        ),
        migrations.AlterField(
            model_name="week",
            name="footer",
            field=models.TextField(verbose_name="Fußzeile"),
        ),
        migrations.AlterField(
            model_name="week",
            name="headline",
            field=models.TextField(verbose_name="Überschrift"),
        ),
    ]
