# Generated by Django 4.1 on 2022-08-29 11:22

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0004_meal_order_alter_week_footer_alter_week_headline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="date",
        ),
        migrations.AlterField(
            model_name="week",
            name="footer",
            field=models.TextField(blank=True, verbose_name="Fußzeile"),
        ),
        migrations.AlterField(
            model_name="week",
            name="headline",
            field=models.TextField(blank=True, verbose_name="Überschrift"),
        ),
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created"),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("concealed", models.BooleanField(default=False, editable=False)),
                ("date", models.DateField()),
                ("meals", models.ManyToManyField(to="meals.meal")),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="meals.week"
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "get_latest_by": "created",
                "abstract": False,
                "base_manager_name": "data",
                "default_manager_name": "data",
            },
            managers=[
                ("data", django.db.models.manager.Manager()),
            ],
        ),
    ]
