# Generated by Django 4.1 on 2022-08-29 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0006_dayentry_remove_meal_order_alter_meal_headline_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created"),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("concealed", models.BooleanField(default=False, editable=False)),
                ("date", models.DateField()),
            ],
            options={
                "ordering": ["-created"],
                "get_latest_by": "created",
                "abstract": False,
                "base_manager_name": "data",
                "default_manager_name": "data",
            },
            managers=[
                ("data", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created"),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("concealed", models.BooleanField(default=False, editable=False)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=7, verbose_name="Preis"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sortierung")),
                (
                    "day",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="meals.day"),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="meals.meal"
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "get_latest_by": "created",
                "abstract": False,
                "base_manager_name": "data",
                "default_manager_name": "data",
            },
            managers=[
                ("data", django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name="DayEntry",
        ),
        migrations.AddField(
            model_name="day",
            name="meals",
            field=models.ManyToManyField(through="meals.Plan", to="meals.meal"),
        ),
        migrations.AddField(
            model_name="day",
            name="week",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="meals.week"),
        ),
    ]
