# Generated by Django 4.1.1 on 2022-09-09 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0007_day_plan_delete_dayentry_day_meals_day_week"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="day",
            options={
                "base_manager_name": "data",
                "default_manager_name": "data",
                "get_latest_by": "created",
                "ordering": ("date",),
            },
        ),
        migrations.AlterModelOptions(
            name="plan",
            options={
                "base_manager_name": "data",
                "default_manager_name": "data",
                "get_latest_by": "created",
                "ordering": ("order",),
            },
        ),
        migrations.RemoveField(
            model_name="meal",
            name="price",
        ),
        migrations.AlterField(
            model_name="day",
            name="week",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="days", to="meals.week"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="plans", to="meals.day"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="meal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="plans", to="meals.meal"
            ),
        ),
    ]
