# Generated by Django 4.1.1 on 2022-09-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0008_alter_day_options_alter_plan_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meal",
            options={
                "base_manager_name": "data",
                "default_manager_name": "data",
                "get_latest_by": "created",
                "ordering": ["name"],
                "verbose_name": "Mahlzeit",
                "verbose_name_plural": "Mahlzeiten",
            },
        ),
        migrations.AlterModelOptions(
            name="plan",
            options={
                "base_manager_name": "data",
                "default_manager_name": "data",
                "get_latest_by": "created",
                "ordering": ("order", "created"),
            },
        ),
        migrations.AddField(
            model_name="week",
            name="published",
            field=models.BooleanField(default=False, verbose_name="veröffentlicht"),
        ),
        migrations.AlterField(
            model_name="plan",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, verbose_name="Preis"
            ),
        ),
    ]
