# Generated by Django 4.1.1 on 2022-09-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0009_alter_meal_options_alter_plan_options_week_published_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="alt_text",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="day",
            name="closed",
            field=models.BooleanField(default=False, verbose_name="geschlossen"),
        ),
    ]
