# Generated by Django 4.1.1 on 2022-09-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0010_day_alt_text_day_closed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="week",
            options={
                "base_manager_name": "data",
                "default_manager_name": "data",
                "get_latest_by": "created",
                "ordering": ["-start"],
            },
        ),
        migrations.AlterField(
            model_name="day",
            name="date",
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name="week",
            name="start",
            field=models.DateField(unique=True, verbose_name="Wochenstart"),
        ),
    ]
