# Generated by Django 4.1.1 on 2022-09-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0011_alter_week_options_alter_day_date_alter_week_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="alt_text",
            field=models.TextField(blank=True),
        ),
    ]
