# Generated by Django 4.1.2 on 2022-11-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0012_alter_day_alt_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="day",
            options={
                "base_manager_name": "data",
                "default_manager_name": "data",
                "get_latest_by": "created",
                "ordering": ("date",),
                "verbose_name": "Tag",
                "verbose_name_plural": "Tage",
            },
        ),
        migrations.AlterModelOptions(
            name="meal",
            options={
                "base_manager_name": "data",
                "default_manager_name": "data",
                "get_latest_by": "created",
                "ordering": ["name"],
                "verbose_name": "Gericht",
                "verbose_name_plural": "Gerichte",
            },
        ),
        migrations.AlterModelOptions(
            name="week",
            options={
                "base_manager_name": "data",
                "default_manager_name": "data",
                "get_latest_by": "created",
                "ordering": ["-start"],
                "verbose_name": "Woche",
                "verbose_name_plural": "Wochen",
            },
        ),
        migrations.AddField(
            model_name="meal",
            name="vegan",
            field=models.BooleanField(default=False, verbose_name="vegan"),
        ),
    ]
