# Generated by Django 4.1.3 on 2022-11-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0014_alter_meal_headline"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="highlight",
            field=models.BooleanField(default=False, verbose_name="Highlight"),
        ),
    ]
