# Generated by Django 4.2.7 on 2024-01-07 14:09

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0016_suggestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created"),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("concealed", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("logo", models.ImageField(blank=True, upload_to="logos", verbose_name="Logo")),
            ],
            options={
                "ordering": ["-created"],
                "get_latest_by": "created",
                "abstract": False,
                "base_manager_name": "data",
                "default_manager_name": "data",
            },
            managers=[
                ("data", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="suggestion",
            options={
                "base_manager_name": "data",
                "default_manager_name": "data",
                "get_latest_by": "created",
                "ordering": ["seen", "created"],
                "verbose_name": "Vorschlag",
                "verbose_name_plural": "Vorschläge",
            },
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="seen",
            field=models.BooleanField(default=False, verbose_name="gesehen"),
        ),
        migrations.AlterField(
            model_name="week",
            name="start",
            field=models.DateField(verbose_name="Wochenstart"),
        ),
    ]
