# Generated by Django 4.2.7 on 2024-01-07 14:10

from django.db import migrations


def create_locations(apps, schema_editor):
    Location = apps.get_model("meals", "Location")
    Location.data.create(name="Krimis Familienbande", logo="")
    Location.data.create(name="Luises Familienbande", logo="")


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0017_location_alter_suggestion_options_and_more"),
    ]

    operations = [
        migrations.RunPython(create_locations, reverse_code=migrations.RunPython.noop)
    ]
