# Generated by Django 4.2.7 on 2024-01-07 14:10

from django.db import migrations


def create_locations(apps, schema_editor):
    Location = apps.get_model("meals", "Location")
    Location.data.create(
        name="Krimis Familienbande",
        logo="logos/logo.png",
        # headline='<p><strong>Miersdorfer Chaussee 9, 15738 Zeuthen - Verkauf 11-14 Uhr</strong></p>',
    )
    Location.data.create(
        name="Luises Familienbande",
        logo="logos/logo-luise.png",
        # headline='<p><strong>Fontaneallee 27-28, 15738 Zeuthen - Verkauf 11-14 Uhr</strong></p>',
    )


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0017_location_alter_suggestion_options_and_more"),
    ]

    operations = [
        migrations.RunPython(create_locations, reverse_code=migrations.RunPython.noop)
    ]
