# Generated by Django 4.2.7 on 2024-01-07 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0018_auto_20240107_1510"),
    ]

    operations = [
        migrations.AddField(
            model_name="week",
            name="location",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weeks",
                to="meals.location",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="week",
            constraint=models.UniqueConstraint(fields=("location", "start"), name="unique_week"),
        ),
    ]
