# Generated by Django 4.2.11 on 2024-04-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0019_week_location_week_unique_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="date",
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name="day",
            constraint=models.UniqueConstraint(fields=("date", "week"), name="unique_day"),
        ),
    ]
