# Generated by Django 4.2.11 on 2024-04-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0020_alter_day_date_day_unique_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="headline",
            field=models.TextField(blank=True, verbose_name="Überschrift"),
        ),
    ]
