# Generated by Django 4.2.11 on 2024-04-15 15:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0021_location_headline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="headline",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="Überschrift"),
        ),
    ]
