# Generated by Django 4.2.11 on 2024-04-29 07:24

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0022_alter_location_headline"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created"),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("concealed", models.BooleanField(default=False, editable=False)),
                ("date", models.DateField(unique=True)),
                ("page_counter", models.IntegerField(default=0)),
                ("alexa_counter", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-created"],
                "get_latest_by": "created",
                "abstract": False,
                "base_manager_name": "data",
                "default_manager_name": "data",
            },
            managers=[
                ("data", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="meal",
            name="headline",
            field=models.BooleanField(
                default=False,
                help_text="Fett geschrieben, ohne Preisanzeige",
                verbose_name="Wahlessen",
            ),
        ),
    ]
