# Generated by Django 4.2.11 on 2024-04-29 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0023_stats_alter_meal_headline"),
    ]

    operations = [
        migrations.AddField(
            model_name="week",
            name="special_menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="meals.plan",
            ),
        ),
    ]
