# Generated by Django 4.2.11 on 2024-04-29 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0024_week_special_menu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="day",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plans",
                to="meals.day",
            ),
        ),
        migrations.AlterField(
            model_name="week",
            name="special_menu",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="meals.plan",
                verbose_name="Gericht der Woche",
            ),
        ),
    ]
