# Generated by Django 4.2.16 on 2024-12-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0026_customer_alter_week_start"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
