# Generated by Django 5.1.6 on 2025-02-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0027_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='concealed',
        ),
        migrations.RemoveField(
            model_name='day',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='location',
            name='concealed',
        ),
        migrations.RemoveField(
            model_name='location',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='concealed',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='concealed',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='concealed',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='concealed',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='week',
            name='concealed',
        ),
        migrations.RemoveField(
            model_name='week',
            name='deleted',
        ),
    ]
