# Generated by Django 4.2.16 on 2024-12-13 16:35

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created"),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("concealed", models.BooleanField(default=False, editable=False)),
                (
                    "salutation",
                    models.CharField(choices=[("Herr", "Herr"), ("Frau", "Frau")], max_length=200),
                ),
                ("company", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("street", models.CharField(max_length=200)),
                ("zip", models.CharField(max_length=5)),
                ("city", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
            options={
                "verbose_name": "Kunde",
                "verbose_name_plural": "Kunden",
                "ordering": ["name"],
                "get_latest_by": "created",
                "abstract": False,
                "base_manager_name": "data",
                "default_manager_name": "data",
            },
            managers=[
                ("data", django.db.models.manager.Manager()),
            ],
        ),
    ]
