# Generated by Django 4.2.16 on 2024-12-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_alter_customer_city_alter_customer_company_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="items",
        ),
    ]
