# Generated by Django 4.2.16 on 2024-12-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0003_remove_invoice_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="net",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, null=True, verbose_name="Netto"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="tax",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, null=True, verbose_name="MwSt."
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, null=True, verbose_name="Brutto"
            ),
        ),
    ]
