# Generated by Django 4.2.16 on 2025-01-09 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0004_alter_invoice_net_alter_invoice_tax_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="invoices.customer",
                verbose_name="Kunde",
            ),
        ),
    ]
