# Generated by Django 4.2.17 on 2025-01-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0005_alter_invoice_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="city",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="company",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="salutation",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="street",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="zip",
        ),
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.TextField(default="", verbose_name="Adresse"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
