# Generated by Django 4.2.17 on 2025-01-26 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0006_remove_customer_city_remove_customer_company_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                (
                    "combining_dates",
                    models.BooleanField(default=False, verbose_name="Kombinierte Rechnungen"),
                ),
                ("delivered", models.BooleanField(default=False, verbose_name="Geliefert")),
            ],
            options={
                "verbose_name": "Rechnungstag",
                "verbose_name_plural": "Rechnungstage",
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="delivery",
            field=models.BooleanField(default=False, verbose_name="Lieferung"),
        ),
        migrations.CreateModel(
            name="InvoiceMeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Preis"),
                ),
                ("delivered", models.BooleanField(default=False, verbose_name="Geliefert")),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to="invoices.invoiceday",
                        verbose_name="Rechnungstag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rechnungsessen",
                "verbose_name_plural": "Rechnungsessen",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="invoiceday",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_days",
                to="invoices.customer",
                verbose_name="Kunde",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="days",
            field=models.ManyToManyField(
                related_name="invoices", to="invoices.invoiceday", verbose_name="Rechnungstage"
            ),
        ),
    ]
