# Generated by Django 4.2.17 on 2025-02-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0008_remove_customer_delivery_customer_delivery_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoicemeal",
            options={
                "ordering": ["name"],
                "verbose_name": "Rechnungposition",
                "verbose_name_plural": "Rechnungspositionen",
            },
        ),
        migrations.AddField(
            model_name="invoicemeal",
            name="count",
            field=models.IntegerField(default=1),
        ),
    ]
