# Generated by Django 4.2.17 on 2025-02-23 10:06

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0009_alter_invoicemeal_options_invoicemeal_count"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="invoiceday",
            managers=[
                ("data", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="invoicemeal",
            managers=[
                ("data", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="invoiceday",
            name="concealed",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="invoiceday",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoiceday",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="invoiceday",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="invoicemeal",
            name="concealed",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="invoicemeal",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoicemeal",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="invoicemeal",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
