# Generated by Django 4.2.17 on 2025-02-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0010_alter_invoiceday_managers_alter_invoicemeal_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoiceday",
            options={
                "ordering": ["date"],
                "verbose_name": "Rechnungstag",
                "verbose_name_plural": "Rechnungstage",
            },
        ),
        migrations.AlterModelOptions(
            name="invoicemeal",
            options={
                "ordering": ["created"],
                "verbose_name": "Rechnungposition",
                "verbose_name_plural": "Rechnungspositionen",
            },
        ),
        migrations.AddField(
            model_name="invoicemeal",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Kommentar"),
        ),
    ]
