# Generated by Django 5.1.6 on 2025-02-28 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_remove_invoice_days_invoiceday_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='concealed',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='concealed',
        ),
        migrations.RemoveField(
            model_name='invoiceday',
            name='concealed',
        ),
        migrations.RemoveField(
            model_name='invoicemeal',
            name='concealed',
        ),
    ]
