# Generated by Django 5.1.6 on 2025-02-28 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_remove_customer_concealed_remove_invoice_concealed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='invoiceday',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='invoicemeal',
            name='deleted',
        ),
    ]
