# Generated by Django 5.2 on 2025-05-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_remove_customer_deleted_remove_invoice_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'base_manager_name': 'data', 'default_manager_name': 'data', 'get_latest_by': 'created', 'ordering': ['-invoice_number'], 'verbose_name': 'Rechnung', 'verbose_name_plural': 'Rechnungen'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Rechnungstext'),
        ),
    ]
