# Generated by Django 5.2.3 on 2025-12-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_alter_invoice_options_invoice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bank_account',
            field=models.CharField(choices=[('bank', 'Sparkasse'), ('sumup', 'SumUp')], default='bank', max_length=200, verbose_name='Zahlungsart'),
        ),
    ]
